import type { CodexDockError, CodexEvent, JsonObject, JsonValue } from "@codexdock/protocol";
import { makeCodexDockError } from "@codexdock/protocol";

export interface CodexInvokeInput {
  invocationId: string;
  type: string;
  prompt: string;
  payload: JsonObject;
}

export interface CodexInvokeResult {
  result: JsonValue;
  logs?: CodexEvent[];
}

export interface CodexEventSink {
  emit(event: CodexEvent): Promise<void>;
}

export interface CodexDoctorResult {
  ok: boolean;
  codexAvailable: boolean;
  authenticated: boolean;
  message?: string;
  error?: CodexDockError;
}

export interface CodexAdapter {
  doctor(): Promise<CodexDoctorResult>;
  invoke(input: CodexInvokeInput, events: CodexEventSink): Promise<CodexInvokeResult>;
}

export interface SdkCodexAdapterOptions {
  workingDirectory?: string;
  skipGitRepoCheck?: boolean;
}

export class ConsoleEventSink implements CodexEventSink {
  async emit(event: CodexEvent): Promise<void> {
    const prefix = `[${event.level}]`;
    if (event.level === "error") {
      console.error(prefix, event.message, event.payload ?? "");
      return;
    }
    console.log(prefix, event.message, event.payload ?? "");
  }
}

export class MemoryEventSink implements CodexEventSink {
  readonly events: CodexEvent[] = [];

  async emit(event: CodexEvent): Promise<void> {
    this.events.push(event);
  }
}

export class FakeCodexAdapter implements CodexAdapter {
  async doctor(): Promise<CodexDoctorResult> {
    return {
      ok: true,
      codexAvailable: true,
      authenticated: true,
      message: "Fake Codex adapter is ready.",
    };
  }

  async invoke(input: CodexInvokeInput, events: CodexEventSink): Promise<CodexInvokeResult> {
    await events.emit({
      level: "info",
      message: "Fake Codex invocation started.",
      payload: { invocationId: input.invocationId, type: input.type },
    });

    const result = buildFakeResult(input);

    await events.emit({
      level: "info",
      message: "Fake Codex invocation completed.",
      payload: { invocationId: input.invocationId },
    });

    return { result };
  }
}

export class SdkCodexAdapter implements CodexAdapter {
  constructor(private readonly options: SdkCodexAdapterOptions = {}) {}

  async doctor(): Promise<CodexDoctorResult> {
    try {
      const sdk = await import("@openai/codex-sdk");
      if (!("Codex" in sdk)) {
        return {
          ok: false,
          codexAvailable: false,
          authenticated: false,
          error: makeCodexDockError(
            "CODEX_NOT_AVAILABLE",
            "The installed @openai/codex-sdk package does not expose Codex.",
          ),
        };
      }

      return {
        ok: true,
        codexAvailable: true,
        authenticated: true,
        message: "@openai/codex-sdk is installed.",
      };
    } catch (error) {
      return {
        ok: false,
        codexAvailable: false,
        authenticated: false,
        error: makeCodexDockError(
          "CODEX_NOT_AVAILABLE",
          error instanceof Error ? error.message : "Codex SDK is not available.",
        ),
      };
    }
  }

  async invoke(input: CodexInvokeInput, events: CodexEventSink): Promise<CodexInvokeResult> {
    try {
      await events.emit({
        level: "info",
        message: "Codex SDK invocation started.",
        payload: { invocationId: input.invocationId, type: input.type },
      });

      const sdk = await import("@openai/codex-sdk");
      const Codex = (sdk as unknown as { Codex?: new () => unknown }).Codex;
      if (!Codex) {
        throw new Error("@openai/codex-sdk does not expose Codex.");
      }

      const codex = new Codex() as {
        startThread: (options?: SdkCodexAdapterOptions) => {
          run: (prompt: string) => Promise<unknown>;
        };
      };
      const thread = codex.startThread(this.options);
      const runResult = await thread.run(buildPrompt(input));

      await events.emit({
        level: "info",
        message: "Codex SDK invocation completed.",
        payload: { invocationId: input.invocationId },
      });

      return {
        result: normalizeCodexResult(runResult),
      };
    } catch (error) {
      await events.emit({
        level: "error",
        message: "Codex SDK invocation failed.",
        payload: { message: error instanceof Error ? error.message : String(error) },
      });
      throw error;
    }
  }
}

export function createAdapter(
  kind: "fake" | "sdk" = "fake",
  options: SdkCodexAdapterOptions = {},
): CodexAdapter {
  if (kind === "sdk") return new SdkCodexAdapter(options);
  return new FakeCodexAdapter();
}

function buildFakeResult(input: CodexInvokeInput): JsonValue {
  if (input.type === "generate_file") {
    const targetPath = stringFromPayload(input.payload, "targetPath", "README.md");
    return {
      summary: `Generated ${targetPath}.`,
      filename: targetPath,
      content:
        `# ${titleFromPrompt(input.prompt)}\n\n` +
        "Generated by the CodexDock fake adapter.\n\n" +
        "## Prompt\n\n" +
        input.prompt +
        "\n",
    };
  }

  if (input.type === "generate_image_plan") {
    return {
      summary: "Generated image planning data.",
      imagePrompt: `Create a clean product visual for: ${input.prompt}`,
      layout: {
        format: "square",
        subject: "CodexDock generated output",
        mood: "clear, technical, useful",
      },
      palette: ["#0f766e", "#20221f", "#f7f7f4"],
    };
  }

  const count = numberFromPayload(input.payload, "count", 5);
  return {
    summary: "Generated structured data.",
    items: Array.from({ length: count }, (_, index) => ({
      id: index + 1,
      title: `${titleFromPrompt(input.prompt)} ${index + 1}`,
      description: "Fake adapter output. Replace with the Codex SDK adapter for real runs.",
    })),
  };
}

function buildPrompt(input: CodexInvokeInput): string {
  return [
    "You are running as a local Codex worker for CodexDock.",
    "Return a concise result that can be stored as JSON by the host app.",
    "",
    `Invocation type: ${input.type}`,
    "",
    "Prompt:",
    input.prompt,
    "",
    "Payload:",
    JSON.stringify(input.payload, null, 2),
  ].join("\n");
}

function normalizeCodexResult(result: unknown): JsonValue {
  if (typeof result === "string") {
    return { summary: result };
  }

  if (result && typeof result === "object") {
    const record = result as Record<string, unknown>;
    const finalResponse = record.finalResponse ?? record.final_response ?? record.response;
    if (typeof finalResponse === "string") {
      return { summary: finalResponse };
    }
    return toJsonValue(record);
  }

  return { summary: String(result) };
}

function toJsonValue(value: unknown): JsonValue {
  if (
    value === null ||
    typeof value === "string" ||
    typeof value === "number" ||
    typeof value === "boolean"
  ) {
    return value;
  }

  if (Array.isArray(value)) {
    return value.map(toJsonValue);
  }

  if (value && typeof value === "object") {
    const output: Record<string, JsonValue> = {};
    for (const [key, child] of Object.entries(value)) {
      output[key] = toJsonValue(child);
    }
    return output;
  }

  return String(value);
}

function stringFromPayload(payload: JsonObject, key: string, fallback: string): string {
  const value = payload[key];
  return typeof value === "string" && value.trim() ? value : fallback;
}

function numberFromPayload(payload: JsonObject, key: string, fallback: number): number {
  const value = payload[key];
  if (typeof value !== "number" || !Number.isFinite(value)) return fallback;
  return Math.max(1, Math.min(20, Math.trunc(value)));
}

function titleFromPrompt(prompt: string): string {
  return (
    prompt
      .replace(/[^a-zA-Z0-9 ]+/g, " ")
      .trim()
      .split(/\s+/)
      .slice(0, 5)
      .join(" ") || "Generated Output"
  );
}
